import type { Player } from "./models";

export const PLAYERS: Player[] = [
  // --- 投手 ---
  {
    id: "P_松井裕樹",
    name: "松井 裕樹",
    type: "P",
    number: 1,
    team: "サンディエゴ・パドレス",
    group: "投手",
  },
  {
    id: "P_宮城大弥",
    name: "宮城 大弥",
    type: "P",
    number: 13,
    team: "オリックス・バファローズ",
    group: "投手",
  },
  {
    id: "P_伊藤大海",
    name: "伊藤 大海",
    type: "P",
    number: 14,
    team: "北海道日本ハムファイターズ",
    group: "投手",
  },
  {
    id: "P_大勢",
    name: "大勢",
    type: "P",
    number: 15,
    team: "読売ジャイアンツ",
    group: "投手",
  },
  {
    id: "P_大谷翔平",
    name: "大谷 翔平",
    type: "P",
    number: 16,
    team: "ロサンゼルス・ドジャース",
    group: "投手",
  },
  {
    id: "P_菊池雄星",
    name: "菊池 雄星",
    type: "P",
    number: 17,
    team: "ロサンゼルス・エンゼルス",
    group: "投手",
  },
  {
    id: "P_山本由伸",
    name: "山本 由伸",
    type: "P",
    number: 18,
    team: "ロサンゼルス・ドジャース",
    group: "投手",
  },
  {
    id: "P_菅野智之",
    name: "菅野 智之",
    type: "P",
    number: 19,
    team: "（FA）",
    group: "投手",
  },
  {
    id: "P_種市篤暉",
    name: "種市 篤暉",
    type: "P",
    number: 26,
    team: "千葉ロッテマリーンズ",
    group: "投手",
  },
  {
    id: "P_髙橋宏斗",
    name: "髙橋 宏斗",
    type: "P",
    number: 28,
    team: "中日ドラゴンズ",
    group: "投手",
  },
  {
    id: "P_曽谷龍平",
    name: "曽谷 龍平",
    type: "P",
    number: 47,
    team: "オリックス・バファローズ",
    group: "投手",
  },
  {
    id: "P_北山亘基",
    name: "北山 亘基",
    type: "P",
    number: 57,
    team: "北海道日本ハムファイターズ",
    group: "投手",
  },
  {
    id: "P_平良海馬",
    name: "平良 海馬",
    type: "P",
    number: 61,
    team: "埼玉西武ライオンズ",
    group: "投手",
  },
  {
    id: "P_松本裕樹",
    name: "松本 裕樹",
    type: "P",
    number: 66,
    team: "福岡ソフトバンクホークス",
    group: "投手",
  },
  {
    id: "P_石井大智",
    name: "石井 大智",
    type: "P",
    number: 69,
    team: "阪神タイガース",
    group: "投手",
  },

  // --- 野手 ---
  {
    id: "B_若月健矢",
    name: "若月 健矢",
    type: "B",
    number: 4,
    team: "オリックス・バファローズ",
    group: "捕手",
  },
  {
    id: "B_坂本誠志郎",
    name: "坂本 誠志郎",
    type: "B",
    number: 12,
    team: "阪神タイガース",
    group: "捕手",
  },
  {
    id: "B_中村悠平",
    name: "中村 悠平",
    type: "B",
    number: 27,
    team: "東京ヤクルトスワローズ",
    group: "捕手",
  },

  {
    id: "B_牧秀悟",
    name: "牧 秀悟",
    type: "B",
    number: 2,
    team: "横浜DeNAベイスターズ",
    group: "内野手",
  },
  {
    id: "B_小園海斗",
    name: "小園 海斗",
    type: "B",
    number: 3,
    team: "広島東洋カープ",
    group: "内野手",
  },
  {
    id: "B_牧原大成",
    name: "牧原 大成",
    type: "B",
    number: 5,
    team: "福岡ソフトバンクホークス",
    group: "内野手",
  },
  {
    id: "B_源田壮亮",
    name: "源田 壮亮",
    type: "B",
    number: 6,
    team: "埼玉西武ライオンズ",
    group: "内野手",
  },
  {
    id: "B_佐藤輝明",
    name: "佐藤 輝明",
    type: "B",
    number: 7,
    team: "阪神タイガース",
    group: "内野手",
  },
  {
    id: "B_岡本和真",
    name: "岡本 和真",
    type: "B",
    number: 25,
    team: "トロント・ブルージェイズ",
    group: "内野手",
  },
  {
    id: "B_村上宗隆",
    name: "村上 宗隆",
    type: "B",
    number: 55,
    team: "シカゴ・ホワイトソックス",
    group: "内野手",
  },

  {
    id: "B_近藤健介",
    name: "近藤 健介",
    type: "B",
    number: 8,
    team: "福岡ソフトバンクホークス",
    group: "外野手",
  },
  {
    id: "B_周東佑京",
    name: "周東 佑京",
    type: "B",
    number: 20,
    team: "福岡ソフトバンクホークス",
    group: "外野手",
  },
  {
    id: "B_森下翔太",
    name: "森下 翔太",
    type: "B",
    number: 23,
    team: "阪神タイガース",
    group: "外野手",
  },
  {
    id: "B_鈴木誠也",
    name: "鈴木 誠也",
    type: "B",
    number: 51,
    team: "シカゴ・カブス",
    group: "外野手",
  },
];
